### ISSUE TITLE
Cannot upload artifacts with :circleci image

### ISSUE THREAD

**Issue by dramforever** [TerrorJack/vanilla#1]
The `store_artifacts` step on this image succeeds, but no artifact is actually saved and this is the log of the step

    Uploading /home/vanilla/project/artifacts to home/vanilla/project/artifacts
    Uploading /home/vanilla/project/artifacts/out.txt (12 B): FAILED with error RequestError: send request failed
    caused by: Put https://circle-production-customer-artifacts.s3.amazonaws.com/picard/5a5ae37ac9e77c00014e4d66/5a5ae37bc9e77c00014e4d67-0-build/artifacts/home/vanilla/project/artifacts/out.txt: x509: failed to load system roots and no roots provided

You can see a repro here: https://circleci.com/gh/dramforever/terrorjack-vanilla-bug/1 . As you can see, the artifact failed to upload.

**Comment by TerrorJack** [comment]
@dramforever Apologies for replying late, I will look into it now.

**Comment by TerrorJack** [comment]
@dramforever It works now. Updated images are pushed.

**Comment by dramforever** [comment]
Thanks!
